name: youtube_extractor
version: 1.0.0
author: SoundByte (Dominic Maas) <soundbyteuwp@gmail.com>
description: A library for extracting YouTube audio and video streams.
homepage: https://github.com/SoundByteOSS/youtube-extractor
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: ^0.12.0
  xml: ^3.2.3
